package com.nsalazar.quicktask.task.application.dto.response;

import lombok.Data;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) for task API responses.
 *
 * <p>This class encapsulates complete task data that is returned to clients in API responses.
 * It serves as a contract between the server and API consumers, providing all relevant task
 * information including metadata such as creation and modification timestamps.
 *
 * <p><strong>Usage Context:</strong>
 * This DTO is used in the response body for the following REST endpoints:
 * <ul>
 *   <li>GET {@code /api/v1/tasks} - Returns a paginated list of TaskDTOResponse objects</li>
 *   <li>GET {@code /api/v1/tasks/{id}} - Returns a single TaskDTOResponse object</li>
 *   <li>POST {@code /api/v1/tasks} - Returns the created TaskDTOResponse object</li>
 *   <li>PUT {@code /api/v1/tasks/{id}} - Returns the updated TaskDTOResponse object</li>
 * </ul>
 *
 * <p><strong>Response Format Example:</strong>
 * <pre>
 * {
 *   "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
 *   "title": "Complete project documentation",
 *   "description": "Write comprehensive documentation for all API endpoints",
 *   "completed": false,
 *   "createdAt": "2026-02-19T10:30:00",
 *   "updatedAt": null
 * }
 * </pre>
 *
 * <p><strong>Lifecycle:</strong>
 * <ol>
 *   <li>Service layer processes task operation (create, read, update)</li>
 *   <li>Mapper converts domain Task object to this DTO</li>
 *   <li>Controller wraps DTO in ResponseEntity with appropriate HTTP status code</li>
 *   <li>Spring serializes DTO to JSON format</li>
 *   <li>JSON response is sent to the client</li>
 * </ol>
 *
 * <p><strong>Read-Only Nature:</strong>
 * This DTO is designed to be read-only from the client perspective. All fields are populated
 * by the server based on the internal state of the Task domain object. Clients cannot modify
 * these values directly - modifications must be made through dedicated update endpoints
 * using TaskDTOUpdateRequest.
 *
 * <p><strong>Timestamp Behavior:</strong>
 * <ul>
 *   <li>{@code createdAt} - Set when the task is created and never changes</li>
 *   <li>{@code updatedAt} - Set when the task is updated, null initially after creation until first update</li>
 * </ul>
 *
 * @author nsalazar
 * @see com.nsalazar.quicktask.task.domain.Task
 * @see com.nsalazar.quicktask.task.application.ITaskService
 * @see com.nsalazar.quicktask.task.infrastructure.restcontroller.TaskController
 * @see com.nsalazar.quicktask.task.application.dto.request.TaskDTOCreateRequest
 * @see com.nsalazar.quicktask.task.application.dto.request.TaskDTOUpdateRequest
 */
@Data
public class TaskDTOResponse {

    /**
     * The unique identifier of the task.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: UUID (Universally Unique Identifier)</li>
     *   <li>Generated by the database during task creation</li>
     *   <li>Immutable - never changes after creation</li>
     *   <li>Always non-null in responses</li>
     *   <li>Used to uniquely identify and reference tasks in subsequent API calls</li>
     * </ul>
     *
     * <p><strong>Example Values:</strong>
     * <ul>
     *   <li>f47ac10b-58cc-4372-a567-0e02b2c3d479</li>
     *   <li>a1b2c3d4-e5f6-7890-abcd-ef1234567890</li>
     * </ul>
     *
     * <p><strong>Usage:</strong>
     * The id is used as a path parameter in subsequent API requests to reference the specific task:
     * <pre>
     * GET /api/v1/tasks/{id}
     * PUT /api/v1/tasks/{id}
     * DELETE /api/v1/tasks/{id}
     * </pre>
     */
    private UUID id;

    /**
     * The title of the task.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: String</li>
     *   <li>Required field - always present in responses</li>
     *   <li>Maximum length: 50 characters</li>
     *   <li>Set during task creation and can be updated</li>
     *   <li>May contain alphanumeric characters, spaces, and special characters</li>
     * </ul>
     *
     * <p><strong>Example Values:</strong>
     * <ul>
     *   <li>"Complete project documentation"</li>
     *   <li>"Fix bug #1234 in authentication module"</li>
     *   <li>"Schedule team meeting - Q1 planning"</li>
     * </ul>
     *
     * <p><strong>Business Meaning:</strong>
     * The title serves as a brief summary or name of the task, providing quick identification
     * of what the task is about. It should be concise yet descriptive.
     */
    private String title;

    /**
     * The description of the task.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: String</li>
     *   <li>Required field - always present in responses</li>
     *   <li>Maximum length: 200 characters</li>
     *   <li>Set during task creation and can be updated</li>
     *   <li>Can contain multiple lines, special characters, and unicode characters</li>
     * </ul>
     *
     * <p><strong>Example Values:</strong>
     * <ul>
     *   <li>"Write comprehensive documentation for all REST API endpoints with examples and error codes"</li>
     *   <li>"Investigate and fix the intermittent authentication failure affecting 5% of users"</li>
     *   <li>"Review architecture design and propose improvements for scalability"</li>
     * </ul>
     *
     * <p><strong>Business Meaning:</strong>
     * The description provides detailed information about the task, including context, objectives,
     * and any additional details needed to understand and complete the task.
     */
    private String description;

    /**
     * The completion status of the task.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: Boolean (true/false)</li>
     *   <li>Default value: false (when task is created)</li>
     *   <li>Can be updated through the PUT endpoint</li>
     *   <li>Represents the current state of task completion</li>
     * </ul>
     *
     * <p><strong>Valid Values:</strong>
     * <ul>
     *   <li>{@code true} - Task has been completed and finished</li>
     *   <li>{@code false} - Task is pending or incomplete</li>
     * </ul>
     *
     * <p><strong>State Transitions:</strong>
     * A task can transition between states multiple times:
     * <ul>
     *   <li>New tasks always start with {@code completed = false}</li>
     *   <li>Can be changed from false to true when work is completed</li>
     *   <li>Can be changed back from true to false if task needs to be reopened</li>
     * </ul>
     *
     * <p><strong>Usage Example:</strong>
     * To mark a task as complete, use the PUT endpoint with {@code "completed": true}
     */
    private boolean completed;

    /**
     * The timestamp when the task was created.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: LocalDateTime (ISO-8601 format)</li>
     *   <li>Set automatically when the task is created</li>
     *   <li>Immutable - never changes after creation</li>
     *   <li>Always non-null in responses</li>
     *   <li>Represented in local date/time format without timezone offset</li>
     * </ul>
     *
     * <p><strong>Format:</strong>
     * {@code YYYY-MM-DDTHH:mm:ss} (Example: 2026-02-19T10:30:00)
     *
     * <p><strong>Server Behavior:</strong>
     * The timestamp is set by the server to the current time when the task is created.
     * It reflects the exact moment the task was persisted to the database.
     *
     * <p><strong>Client Usage:</strong>
     * Clients can use this timestamp to:
     * <ul>
     *   <li>Display when the task was created to the user</li>
     *   <li>Sort tasks by creation date</li>
     *   <li>Implement audit trails or history tracking</li>
     * </ul>
     *
     * <p><strong>Example Value:</strong>
     * {@code 2026-02-19T10:30:45}
     */
    private LocalDateTime createdAt;

    /**
     * The timestamp when the task was last updated.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: LocalDateTime (ISO-8601 format)</li>
     *   <li>Set automatically when the task is updated</li>
     *   <li>Initially null after task creation</li>
     *   <li>Updated to current time whenever task fields are modified</li>
     *   <li>Represented in local date/time format without timezone offset</li>
     * </ul>
     *
     * <p><strong>Format:</strong>
     * {@code YYYY-MM-DDTHH:mm:ss} (Example: 2026-02-19T15:45:30)
     *
     * <p><strong>Null Value Meaning:</strong>
     * If {@code updatedAt} is null, the task has never been updated since creation.
     * The task data is in its original state as provided during creation.
     *
     * <p><strong>Server Behavior:</strong>
     * The timestamp is set by the server to the current time whenever any field of the task
     * is modified through the PUT endpoint. The {@code createdAt} timestamp is always preserved.
     *
     * <p><strong>Client Usage:</strong>
     * Clients can use this timestamp to:
     * <ul>
     *   <li>Display the last modification time to the user</li>
     *   <li>Sort tasks by most recently updated</li>
     *   <li>Detect stale data and implement optimistic locking</li>
     *   <li>Implement activity feeds or recent changes displays</li>
     * </ul>
     *
     * <p><strong>Example Values:</strong>
     * <ul>
     *   <li>{@code 2026-02-19T15:45:30} (task has been updated)</li>
     *   <li>{@code null} (task has never been updated since creation)</li>
     * </ul>
     */
    private LocalDateTime updatedAt;

}
