package com.nsalazar.quicktask.task.application.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) for detailed task API responses.
 *
 * <p>This class provides a detailed view of a task including the information of the
 * {@link com.nsalazar.quicktask.tasklist.domain.TaskList} it belongs to. Unlike
 * {@link TaskDTOResponse} which only contains a {@code taskListId}, this DTO embeds
 * the TaskList's name and description for a richer response.
 *
 * <p><strong>Usage Context:</strong>
 * This DTO is used in the response body for the following REST endpoints:
 * <ul>
 *   <li>GET {@code /api/v1/tasks/{id}} - Returns a single TaskDetailDTOResponse object</li>
 *   <li>POST {@code /api/v1/tasks} - Returns the created TaskDetailDTOResponse object</li>
 *   <li>PUT {@code /api/v1/tasks/{id}} - Returns the updated TaskDetailDTOResponse object</li>
 * </ul>
 *
 * <p><strong>Response Format Example:</strong>
 * <pre>
 * {
 *   "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
 *   "title": "Complete project documentation",
 *   "description": "Write comprehensive documentation for all API endpoints",
 *   "completed": false,
 *   "createdAt": "2026-02-19T10:30:00",
 *   "updatedAt": null,
 *   "taskList": {
 *     "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 *     "name": "Development Tasks",
 *     "description": "All development related tasks"
 *   }
 * }
 * </pre>
 *
 * <p><strong>Difference with {@link TaskDTOResponse}:</strong>
 * <ul>
 *   <li>{@code TaskDTOResponse} contains only {@code taskListId} (UUID) — used in paginated list responses (getAll)</li>
 *   <li>{@code TaskDetailDTOResponse} contains an embedded {@link TaskListInfo} object with full
 *       TaskList details — used in single-entity responses (getById, create, update)</li>
 * </ul>
 *
 * @author nsalazar
 * @see TaskDTOResponse
 * @see TaskListInfo
 * @see com.nsalazar.quicktask.task.domain.Task
 * @see com.nsalazar.quicktask.task.application.ITaskService
 * @see com.nsalazar.quicktask.task.infrastructure.restcontroller.TaskController
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaskDetailDTOResponse {

    /**
     * The unique identifier of the task.
     *
     * <p>Generated by the database during task creation. Immutable and always non-null in responses.
     * Used to uniquely identify and reference tasks in subsequent API calls.
     *
     * <p><strong>Example:</strong> {@code f47ac10b-58cc-4372-a567-0e02b2c3d479}
     */
    private UUID id;

    /**
     * The title of the task.
     *
     * <p>A brief summary or name of the task. Required field, always present in responses.
     * Maximum length: 50 characters.
     *
     * <p><strong>Example:</strong> {@code "Complete project documentation"}
     */
    private String title;

    /**
     * The description of the task.
     *
     * <p>Detailed information about the task including context, objectives, and instructions.
     * Required field, always present in responses. Maximum length: 200 characters.
     *
     * <p><strong>Example:</strong> {@code "Write comprehensive documentation for all API endpoints"}
     */
    private String description;

    /**
     * The completion status of the task.
     *
     * <p>{@code true} indicates the task is completed; {@code false} indicates it is pending.
     * New tasks always start with {@code completed = false}.
     */
    private boolean completed;

    /**
     * The timestamp when the task was created.
     *
     * <p>Set automatically when the task is created and never changes.
     * Format: {@code YYYY-MM-DDTHH:mm:ss}
     *
     * <p><strong>Example:</strong> {@code 2026-02-19T10:30:00}
     */
    private LocalDateTime createdAt;

    /**
     * The timestamp when the task was last updated.
     *
     * <p>Initially null after task creation. Set to the current time whenever the task is modified.
     * A null value indicates the task has never been updated since creation.
     *
     * <p><strong>Example:</strong> {@code 2026-02-19T15:45:30} or {@code null}
     */
    private LocalDateTime updatedAt;

    /**
     * The TaskList information this task belongs to.
     *
     * <p>Contains the id, name and description of the associated TaskList.
     * Can be null if the task is not assigned to any TaskList.
     */
    private TaskListInfo taskList;

    /**
     * Summary information of the TaskList associated with a task.
     *
     * <p>This inner class provides a lightweight representation of a TaskList,
     * containing only the essential identification and descriptive fields.
     * It avoids circular references and unnecessary data in task responses.
     *
     * <p><strong>Response Format Example:</strong>
     * <pre>
     * {
     *   "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
     *   "name": "Development Tasks",
     *   "description": "All development related tasks"
     * }
     * </pre>
     *
     * @author nsalazar
     * @see TaskDetailDTOResponse
     * @see com.nsalazar.quicktask.tasklist.domain.TaskList
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TaskListInfo {

        /**
         * The unique identifier of the TaskList.
         *
         * <p><strong>Example:</strong> {@code a1b2c3d4-e5f6-7890-abcd-ef1234567890}
         */
        private UUID id;

        /**
         * The name of the TaskList.
         *
         * <p><strong>Example:</strong> {@code "Development Tasks"}
         */
        private String name;

        /**
         * The description of the TaskList.
         *
         * <p><strong>Example:</strong> {@code "All development related tasks"}
         */
        private String description;

    }

}

