package com.nsalazar.quicktask.task.domain;

import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Domain model representing a Task.
 *
 * <p>This class encapsulates the core business logic, state, and rules for tasks within the system.
 * It is a pure domain object that is independent of any persistence or presentation concerns.
 * The Task domain model is used throughout the application for business operations and is
 * mapped to/from Data Transfer Objects (DTOs) and database entities at the boundaries.
 *
 * <p><strong>Design Characteristics:</strong>
 * <ul>
 *   <li>Immutable in terms of identity - the id never changes after creation</li>
 *   <li>Mutable in terms of state - properties like title, description, and completed can be modified</li>
 *   <li>Self-contained - includes all data necessary to understand a task</li>
 *   <li>No external dependencies - does not depend on Spring or persistence frameworks</li>
 *   <li>Business-focused - properties and behavior represent real-world concepts</li>
 * </ul>
 *
 * <p><strong>Lifecycle:</strong>
 * <ol>
 *   <li>Task is created through the service layer with a title and description</li>
 *   <li>Database generates a unique UUID as the identifier</li>
 *   <li>createdAt timestamp is set to the current server time</li>
 *   <li>Task can be modified through service layer operations</li>
 *   <li>updatedAt timestamp is set whenever the task is modified</li>
 *   <li>Task can be deleted, removing it from the database</li>
 * </ol>
 *
 * <p><strong>State Management:</strong>
 * <ul>
 *   <li>The {@code completed} flag represents the primary state of the task</li>
 *   <li>Tasks start in an incomplete state (completed = false)</li>
 *   <li>The completed state can be toggled multiple times during the task's lifecycle</li>
 *   <li>Timestamps track when the task was created and last modified</li>
 * </ul>
 *
 * <p><strong>Field Constraints:</strong>
 * <ul>
 *   <li>id: Generated UUID, immutable, always unique globally</li>
 *   <li>title: Required, maximum 50 characters, user-provided</li>
 *   <li>description: Required, maximum 200 characters, user-provided</li>
 *   <li>completed: Boolean, defaults to false, modifiable by users</li>
 *   <li>createdAt: Set once by the system, never modified</li>
 *   <li>updatedAt: Set by the system on creation and on updates, can be null initially</li>
 * </ul>
 *
 * <p><strong>Usage in Architecture:</strong>
 * <ul>
 *   <li>Domain Layer: This class is the core of the domain layer</li>
 *   <li>Service Layer: Operates on Task objects and enforces business rules</li>
 *   <li>Repository Layer: Persists and retrieves Task objects (mapped to TaskEntity)</li>
 *   <li>Mapping Layer: Converts between Task, TaskEntity, and various DTOs</li>
 *   <li>Presentation Layer: Task data is exposed via DTOs in API responses</li>
 * </ul>
 *
 * <p><strong>Builder Pattern:</strong>
 * This class uses Lombok's {@code @Builder} annotation to provide a fluent builder for
 * construction. Example usage:
 * <pre>
 * Task task = Task.builder()
 *     .id(UUID.randomUUID())
 *     .title("Complete documentation")
 *     .description("Write comprehensive documentation for all endpoints")
 *     .completed(false)
 *     .createdAt(LocalDateTime.now())
 *     .build();
 * </pre>
 *
 * @author nsalazar
 * @see com.nsalazar.quicktask.task.infrastructure.database.entity.TaskEntity
 * @see com.nsalazar.quicktask.task.application.dto.response.TaskDTOResponse
 * @see com.nsalazar.quicktask.task.application.ITaskService
 * @see com.nsalazar.quicktask.task.domain.repository.ITaskRepository
 */
@Getter
@Setter
@Builder
public class Task {

    /**
     * The unique identifier of the task.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: UUID (Universally Unique Identifier)</li>
     *   <li>Generated by the database during task persistence</li>
     *   <li>Immutable - never changes after initial assignment</li>
     *   <li>Used as the primary key for database lookups</li>
     *   <li>Globally unique across all systems and time</li>
     * </ul>
     *
     * <p><strong>Lifecycle:</strong>
     * <ul>
     *   <li>Null when a new Task domain object is first created</li>
     *   <li>Assigned a value by the database during the save operation</li>
     *   <li>Retrieved from the database when loading existing tasks</li>
     * </ul>
     *
     * <p><strong>Usage:</strong>
     * <ul>
     *   <li>Used in URLs as path parameter: {@code /api/v1/tasks/{id}}</li>
     *   <li>Used to uniquely identify a task in logs and audit trails</li>
     *   <li>Used to establish relationships to other entities (if any)</li>
     * </ul>
     *
     * <p><strong>Null Handling:</strong>
     * The id may be null in transient Task objects before they are persisted to the database.
     * After persistence, the id is always populated and never null.
     */
    private UUID id;

    /**
     * The title of the task.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: String</li>
     *   <li>Maximum Length: 50 characters (enforced at database level)</li>
     *   <li>Required Field: Cannot be null or empty</li>
     *   <li>User-Provided: Set by the client during task creation</li>
     *   <li>Modifiable: Can be updated through the service layer</li>
     * </ul>
     *
     * <p><strong>Business Purpose:</strong>
     * The title serves as a brief, human-readable name or summary of the task. It should
     * clearly convey the main objective or action required to complete the task.
     *
     * <p><strong>Examples:</strong>
     * <ul>
     *   <li>"Complete project documentation"</li>
     *   <li>"Fix critical authentication bug"</li>
     *   <li>"Schedule Q1 planning meeting"</li>
     *   <li>"Review pull requests"</li>
     * </ul>
     *
     * <p><strong>Constraints & Validation:</strong>
     * <ul>
     *   <li>Cannot be null - validation should reject null values</li>
     *   <li>Cannot be empty string - validation should reject blank values</li>
     *   <li>Cannot be whitespace-only - validation should trim and reject empty results</li>
     *   <li>Must not exceed 50 characters - longer values will be truncated at database level</li>
     *   <li>Can contain unicode characters, special characters, and punctuation</li>
     * </ul>
     *
     * <p><strong>Search & Filtering:</strong>
     * The title is typically indexed for efficient searching and filtering operations.
     * Users often search or filter tasks by keywords in the title.
     */
    private String title;

    /**
     * The description of the task.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: String</li>
     *   <li>Maximum Length: 200 characters (enforced at database level)</li>
     *   <li>Required Field: Cannot be null or empty</li>
     *   <li>User-Provided: Set by the client during task creation</li>
     *   <li>Modifiable: Can be updated through the service layer</li>
     *   <li>Multi-line Capable: Can contain newline characters and formatted text</li>
     * </ul>
     *
     * <p><strong>Business Purpose:</strong>
     * The description provides detailed information about the task, including context,
     * objectives, acceptance criteria, and any other information needed for someone to
     * understand and complete the task successfully.
     *
     * <p><strong>Examples:</strong>
     * <ul>
     *   <li>"Write comprehensive documentation for all REST API endpoints with usage examples and error handling"</li>
     *   <li>"Investigate the intermittent authentication failure and implement a permanent fix. Test with load."</li>
     *   <li>"Review all pending pull requests in the repository and provide constructive feedback"</li>
     * </ul>
     *
     * <p><strong>Constraints & Validation:</strong>
     * <ul>
     *   <li>Cannot be null - validation should reject null values</li>
     *   <li>Cannot be empty string - validation should reject blank values</li>
     *   <li>Cannot be whitespace-only - validation should trim and reject empty results</li>
     *   <li>Must not exceed 200 characters - longer values will be truncated at database level</li>
     *   <li>Can contain unicode characters, special characters, newlines, and formatted text</li>
     * </ul>
     *
     * <p><strong>Content Guidelines:</strong>
     * <ul>
     *   <li>Should be more detailed than the title</li>
     *   <li>Can include bullet points, step-by-step instructions, or requirements</li>
     *   <li>Should provide enough context for someone unfamiliar with the task to understand it</li>
     *   <li>Can include references to external documentation or resources</li>
     * </ul>
     */
    private String description;

    /**
     * The completion status of the task.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: Boolean (true/false)</li>
     *   <li>Default Value: false (new tasks are incomplete by default)</li>
     *   <li>Modifiable: Can be toggled multiple times during the task's lifecycle</li>
     *   <li>User-Controlled: Set and updated by users through the service layer</li>
     *   <li>State Indicator: Primary indicator of task progress</li>
     * </ul>
     *
     * <p><strong>Meaning:</strong>
     * <ul>
     *   <li>{@code false} - Task is pending, incomplete, or in progress</li>
     *   <li>{@code true} - Task is finished, done, or marked as complete</li>
     * </ul>
     *
     * <p><strong>Lifecycle:</strong>
     * <ol>
     *   <li>New tasks always start with {@code completed = false}</li>
     *   <li>Can transition from false to true when work is completed</li>
     *   <li>Can transition from true back to false if reopened for additional work</li>
     *   <li>Can be toggled multiple times as needed</li>
     * </ol>
     *
     * <p><strong>Semantic Implications:</strong>
     * <ul>
     *   <li>Setting to true indicates the task work has been finished</li>
     *   <li>Setting to false indicates the task requires more work or is being reopened</li>
     *   <li>Does not affect other task properties like title, description, or timestamps</li>
     *   <li>Changing this flag triggers an update to the updatedAt timestamp</li>
     * </ul>
     *
     * <p><strong>UI Representation:</strong>
     * <ul>
     *   <li>Often displayed as a checkbox that can be toggled</li>
     *   <li>Completed tasks may be visually distinct (strikethrough, grayed out, etc.)</li>
     *   <li>Users may filter or sort tasks by completion status</li>
     * </ul>
     */
    private boolean completed;

    /**
     * The timestamp when the task was created.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: LocalDateTime (no timezone information)</li>
     *   <li>Set Automatically: Assigned by the service layer during task creation</li>
     *   <li>Immutable: Never modified after initial assignment</li>
     *   <li>Represents: The exact moment the task was persisted to the database</li>
     *   <li>Server Time: Reflects the server's local date and time at creation</li>
     * </ul>
     *
     * <p><strong>Format:</strong>
     * ISO-8601 extended format: {@code YYYY-MM-DDTHH:mm:ss}
     * Example: {@code 2026-02-19T10:30:45}
     *
     * <p><strong>Lifecycle:</strong>
     * <ul>
     *   <li>Null in new Task objects before persistence</li>
     *   <li>Set to {@code LocalDateTime.now()} by the service layer before saving</li>
     *   <li>Retrieved from database when loading existing tasks</li>
     *   <li>Never changes after initial creation</li>
     * </ul>
     *
     * <p><strong>Business Uses:</strong>
     * <ul>
     *   <li>Display when a task was created to users</li>
     *   <li>Sort tasks by creation date (oldest/newest first)</li>
     *   <li>Calculate task age or duration</li>
     *   <li>Implement audit trails and change history</li>
     *   <li>Analyze task creation patterns over time</li>
     * </ul>
     *
     * <p><strong>Important Notes:</strong>
     * <ul>
     *   <li>This timestamp is preserved and never modified, even when the task is updated</li>
     *   <li>The service layer is responsible for setting this value</li>
     *   <li>The repository layer does not modify this field</li>
     * </ul>
     */
    private LocalDateTime createdAt;

    /**
     * The timestamp when the task was last updated.
     *
     * <p><strong>Characteristics:</strong>
     * <ul>
     *   <li>Data Type: LocalDateTime (no timezone information)</li>
     *   <li>Set Automatically: Assigned by the service layer during updates</li>
     *   <li>Mutable: Updated whenever the task is modified</li>
     *   <li>Initially Null: Is null until the task is updated for the first time</li>
     *   <li>Server Time: Reflects the server's local date and time at modification</li>
     * </ul>
     *
     * <p><strong>Format:</strong>
     * ISO-8601 extended format: {@code YYYY-MM-DDTHH:mm:ss}
     * Example: {@code 2026-02-19T15:45:30}
     *
     * <p><strong>Null Handling:</strong>
     * <ul>
     *   <li>Null immediately after task creation (no updates yet)</li>
     *   <li>Populated when any field of the task is updated</li>
     *   <li>A null value indicates the task has never been modified since creation</li>
     * </ul>
     *
     * <p><strong>Lifecycle:</strong>
     * <ol>
     *   <li>New Task: {@code updatedAt = null} (no updates yet)</li>
     *   <li>First Update: {@code updatedAt} set to current server time</li>
     *   <li>Subsequent Updates: {@code updatedAt} updated to reflect the latest change</li>
     *   <li>Always: {@code updatedAt >= createdAt} (update time is always after or equal to creation time)</li>
     * </ol>
     *
     * <p><strong>Business Uses:</strong>
     * <ul>
     *   <li>Display when a task was last modified to users</li>
     *   <li>Sort tasks by most recently updated (for activity feeds)</li>
     *   <li>Detect stale data or outdated task information</li>
     *   <li>Implement optimistic locking and concurrency control</li>
     *   <li>Generate activity logs showing task modification history</li>
     * </ul>
     *
     * <p><strong>Update Triggers:</strong>
     * The updatedAt timestamp is set to the current server time whenever any of the following
     * mutable properties are modified:
     * <ul>
     *   <li>Title</li>
     *   <li>Description</li>
     *   <li>Completed status</li>
     * </ul>
     *
     * <p><strong>Important Notes:</strong>
     * <ul>
     *   <li>The service layer is responsible for setting this value on updates</li>
     *   <li>The createdAt timestamp is preserved and never modified</li>
     *   <li>The repository layer does not automatically update this field</li>
     * </ul>
     */
    private LocalDateTime updatedAt;

}
