package com.nsalazar.quicktask.task.application.dto.mapper;

import com.nsalazar.quicktask.task.application.dto.request.TaskDTOCreateRequest;
import com.nsalazar.quicktask.task.application.dto.request.TaskDTOUpdateRequest;
import com.nsalazar.quicktask.task.application.dto.response.TaskDTOResponse;
import com.nsalazar.quicktask.task.domain.Task;
import org.mapstruct.*;

/**
 * Mapper interface for converting between Task domain objects and Data Transfer Objects (DTOs).
 *
 * <p>This interface uses MapStruct to generate type-safe mapping implementations at compile-time.
 * It provides methods for converting between:
 * <ul>
 *   <li>{@link TaskDTOCreateRequest} - Task creation request DTOs</li>
 *   <li>{@link TaskDTOUpdateRequest} - Task update request DTOs</li>
 *   <li>{@link TaskDTOResponse} - Task response DTOs</li>
 *   <li>{@link Task} - Domain Task objects</li>
 * </ul>
 *
 * <p><strong>MapStruct Configuration:</strong>
 * <ul>
 *   <li>Component Model: Spring - Generates a Spring-managed bean</li>
 *   <li>Unmapped Source Policy: ERROR - Fails compilation if source properties are not mapped</li>
 *   <li>Unmapped Target Policy: ERROR - Fails compilation if target properties are not mapped</li>
 * </ul>
 *
 * <p><strong>Design Principles:</strong>
 * <ul>
 *   <li>Separation of concerns between API contracts (DTOs) and domain objects</li>
 *   <li>Automatic type conversion with explicit control over field handling</li>
 *   <li>Server-generated fields (id, timestamps) are explicitly ignored in request mappings</li>
 *   <li>Immutable fields (createdAt) are protected from updates</li>
 * </ul>
 *
 * @author nsalazar
 * @see Task
 * @see TaskDTOCreateRequest
 * @see TaskDTOUpdateRequest
 * @see TaskDTOResponse
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING,
        unmappedSourcePolicy = ReportingPolicy.ERROR,
        unmappedTargetPolicy = ReportingPolicy.ERROR
)
public interface ITaskDTOMapper {

    /**
     * Converts a task creation request DTO to a domain Task object.
     *
     * <p>This method is used when a client submits a request to create a new task. The conversion
     * extracts the title and description from the request DTO and creates a domain Task object.
     *
     * <p><strong>Field Mapping Behavior:</strong>
     * <ul>
     *   <li>{@code title} - Mapped from DTO to domain object</li>
     *   <li>{@code description} - Mapped from DTO to domain object</li>
     *   <li>{@code id} - Ignored (will be generated by the database)</li>
     *   <li>{@code completed} - Ignored (defaults to false for new tasks, set by service layer)</li>
     *   <li>{@code createdAt} - Ignored (set by service layer to current time)</li>
     *   <li>{@code updatedAt} - Ignored (set to null for new tasks)</li>
     * </ul>
     *
     * <p><strong>Usage Context:</strong>
     * This method is called by the service layer when creating a new task from a client request.
     * Server-generated fields are explicitly ignored to ensure they are not accidentally populated
     * from the client request.
     *
     * @param taskDTOCreateRequest the task creation request DTO containing title and description
     * @return a new {@link Task} domain object with mapped title and description,
     *         with id, completed status, and timestamps left uninitialized for service layer handling
     * @see TaskDTOCreateRequest
     * @see Task
     */
    @Mappings({
            @Mapping(target = "id", ignore = true),
            @Mapping(target = "completed", ignore = true),
            @Mapping(target = "createdAt", ignore = true),
            @Mapping(target = "updatedAt", ignore = true)
    })
    Task toTask(TaskDTOCreateRequest taskDTOCreateRequest);

    /**
     * Updates an existing task domain object with values from an update request DTO.
     *
     * <p>This method is used when a client submits a request to update an existing task. The conversion
     * extracts the new title, description, and completed status from the request DTO and applies them
     * to the existing task domain object (marked with {@code @MappingTarget}).
     *
     * <p><strong>Field Mapping Behavior:</strong>
     * <ul>
     *   <li>{@code title} - Mapped from DTO to domain object (updated)</li>
     *   <li>{@code description} - Mapped from DTO to domain object (updated)</li>
     *   <li>{@code completed} - Mapped from DTO to domain object (updated)</li>
     *   <li>{@code id} - Ignored (preserved from existing object)</li>
     *   <li>{@code createdAt} - Ignored (preserved from existing object, immutable)</li>
     *   <li>{@code updatedAt} - Ignored (set by service layer to current time)</li>
     * </ul>
     *
     * <p><strong>Usage Context:</strong>
     * This method is called by the service layer when updating an existing task with new values
     * from a client request. The target task object is mutated in-place. The update timestamp is
     * explicitly ignored because it must be set by the service layer to the current time, not
     * from the client request.
     *
     * @param taskDTOUpdateRequest the task update request DTO containing new title, description, and completed status
     * @param task the existing {@link Task} domain object to be updated. This object is modified in-place
     *             with values from the DTO. The id and createdAt fields are preserved.
     * @see TaskDTOUpdateRequest
     * @see Task
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mappings({
            @Mapping(target = "id", ignore = true),
            @Mapping(target = "createdAt", ignore = true),
            @Mapping(target = "updatedAt", ignore = true)
    })
    void toTask(TaskDTOUpdateRequest taskDTOUpdateRequest, @MappingTarget Task task);

    /**
     * Converts a domain Task object to a task response DTO.
     *
     * <p>This method is used to convert a domain Task object into a Data Transfer Object (DTO)
     * suitable for sending in API responses. All fields from the domain object are mapped to
     * corresponding fields in the response DTO.
     *
     * <p><strong>Field Mapping Behavior:</strong>
     * <ul>
     *   <li>{@code id} - Mapped from domain object to DTO</li>
     *   <li>{@code title} - Mapped from domain object to DTO</li>
     *   <li>{@code description} - Mapped from domain object to DTO</li>
     *   <li>{@code completed} - Mapped from domain object to DTO</li>
     *   <li>{@code createdAt} - Mapped from domain object to DTO</li>
     *   <li>{@code updatedAt} - Mapped from domain object to DTO</li>
     * </ul>
     *
     * <p><strong>Usage Context:</strong>
     * This method is called by the service layer after retrieving or manipulating a task, just
     * before returning it to the client. It provides a complete view of the task's current state.
     *
     * @param task the domain {@link Task} object to convert
     * @return a {@link TaskDTOResponse} containing all the task's data in DTO format
     * @see TaskDTOResponse
     * @see Task
     */
    TaskDTOResponse toTaskDTOResponse(Task task);

}
