package com.nsalazar.quicktask.tasklist.application.dto.response;

import com.nsalazar.quicktask.task.application.dto.response.TaskDTOResponse;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * DTO for TaskList API responses.
 *
 * <p>Contains all TaskList data including the list of associated tasks.
 *
 * @author nsalazar
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaskListDTOResponse {

    /**
     * The unique identifier of the task list.
     *
     * <p>Generated by the database during creation. Immutable and always non-null in responses.
     */
    private UUID id;

    /**
     * The name of the task list.
     *
     * <p><strong>Example:</strong> {@code "Development Tasks"}
     */
    private String name;

    /**
     * The description of the task list.
     *
     * <p><strong>Example:</strong> {@code "All development related tasks"}
     */
    private String description;

    /**
     * The list of tasks associated with this task list.
     *
     * <p>Contains summary information for each associated task.
     * Can be empty if no tasks are assigned.
     */
    private List<TaskDTOResponse> tasks;

    /**
     * The timestamp when the task list was created.
     *
     * <p>Set automatically during creation and never changes.
     */
    private LocalDateTime createdAt;

    /**
     * The timestamp when the task list was last updated.
     *
     * <p>Initially null after creation. Set to the current time on each update.
     */
    private LocalDateTime updatedAt;

}

