package com.nsalazar.quicktask.task.infrastructure.database.entity;

import com.nsalazar.quicktask.tasklist.infrastructure.database.entity.TaskListEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA Entity representing a Task in the database.
 *
 * <p>This class is a persistence layer entity that maps to the "tbl_tasks" table in the database.
 * It represents the physical storage model of a task and is used by Spring Data JPA to perform
 * database operations. This entity is distinct from the domain Task model and serves as the
 * bridge between the domain layer and the database.
 *
 * <p><strong>Design Pattern:</strong>
 * This class follows the Active Record pattern combined with the Data Mapper pattern, where
 * the entity represents the database table structure but is mapped to/from domain objects
 * through the mapper layer. The entity should not contain business logic; it only represents
 * the database schema.
 *
 * <p><strong>Database Mapping:</strong>
 * <ul>
 *   <li>Table Name: {@code tbl_tasks}</li>
 *   <li>Primary Key: {@code id} (UUID, auto-generated)</li>
 *   <li>All columns have explicit database names using snake_case naming convention</li>
 *   <li>Constraints are enforced at both entity and database levels</li>
 * </ul>
 *
 * <p><strong>Lombok Annotations:</strong>
 * <ul>
 *   <li>{@code @Getter} - Generates getter methods for all fields</li>
 *   <li>{@code @Setter} - Generates setter methods for all fields</li>
 *   <li>{@code @NoArgsConstructor} - Generates a no-argument constructor required by JPA</li>
 *   <li>{@code @AllArgsConstructor} - Generates a constructor with all fields as parameters</li>
 * </ul>
 *
 * <p><strong>JPA Annotations:</strong>
 * <ul>
 *   <li>{@code @Entity} - Marks this class as a JPA entity</li>
 *   <li>{@code @Table} - Specifies the database table name and constraints</li>
 *   <li>{@code @UniqueConstraint} - Enforces unique title. Validation for incomplete-only restriction is handled in service layer</li>
 *   <li>{@code @Id} - Marks the id field as the primary key</li>
 *   <li>{@code @GeneratedValue} - Specifies UUID auto-generation strategy</li>
 *   <li>{@code @Column} - Specifies database column properties (name, constraints, length)</li>
 * </ul>
 *
 * <p><strong>Lifecycle in Architecture:</strong>
 * <ol>
 *   <li>Domain Task objects are converted to TaskEntity objects before persistence</li>
 *   <li>TaskEntity is used by Spring Data JPA for database operations</li>
 *   <li>Database returns TaskEntity objects when querying</li>
 *   <li>TaskEntity objects are converted back to domain Task objects for business logic</li>
 *   <li>Domain Task objects are then converted to DTOs for API responses</li>
 * </ol>
 *
 * <p><strong>Conversion Flow:</strong>
 * <pre>
 * TaskDTOCreateRequest
 *     ↓ (mapped by ITaskDTOMapper)
 * Task (domain model)
 *     ↓ (mapped by ITaskEntityMapper)
 * TaskEntity (persistence model)
 *     ↓ (persisted by Spring Data JPA)
 * [Database Table: tbl_tasks]
 * </pre>
 *
 * <p><strong>Important Notes:</strong>
 * <ul>
 *   <li>This entity should not be returned directly to clients; use DTOs instead</li>
 *   <li>Always convert to/from domain Task objects to maintain separation of concerns</li>
 *   <li>The entity is mutable, but mutations should only happen within transactional boundaries</li>
 *   <li>Lazy loading and eager loading can be configured here if relationships are added</li>
 * </ul>
 *
 * @author nsalazar
 * @see com.nsalazar.quicktask.task.domain.Task
 * @see com.nsalazar.quicktask.task.infrastructure.database.mapper.ITaskEntityMapper
 * @see com.nsalazar.quicktask.task.infrastructure.database.IJPATaskRepository
 * @see com.nsalazar.quicktask.task.application.dto.response.TaskDTOResponse
 */
@Getter
@Setter
@Entity
@Table(
    name = "tbl_tasks",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uk_title_incomplete_tasks",
            columnNames = {"title"}
        )
    }
)
@AllArgsConstructor
@NoArgsConstructor
public class TaskEntity {

    /**
     * The unique identifier of the task.
     *
     * <p><strong>Database Properties:</strong>
     * <ul>
     *   <li>Type: UUID (universally unique identifier)</li>
     *   <li>Strategy: AUTO-GENERATED using UUID strategy</li>
     *   <li>Primary Key: Yes - uniquely identifies each task record</li>
     *   <li>Column Name: {@code id}</li>
     *   <li>Nullable: No (enforced by @Id annotation)</li>
     * </ul>
     *
     * <p><strong>Generation Details:</strong>
     * The UUID is automatically generated by the database using the {@code GenerationType.UUID}
     * strategy. This creates a universally unique 128-bit identifier in standard UUID format.
     *
     * <p><strong>Format Example:</strong>
     * {@code f47ac10b-58cc-4372-a567-0e02b2c3d479}
     *
     * <p><strong>Lifecycle:</strong>
     * <ul>
     *   <li>Generated when the entity is persisted (INSERT)</li>
     *   <li>Immutable - never changes for a given record</li>
     *   <li>Used to retrieve, update, and delete specific tasks</li>
     * </ul>
     *
     * <p><strong>Usage:</strong>
     * The id is used as the primary key for efficient lookups and relationships.
     * It is exposed in API responses and used in URL paths like {@code /api/v1/tasks/{id}}
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The title of the task.
     *
     * <p><strong>Database Properties:</strong>
     * <ul>
     *   <li>Type: VARCHAR(50)</li>
     *   <li>Column Name: {@code title}</li>
     *   <li>Nullable: No - must always have a value</li>
     *   <li>Length: Maximum 50 characters</li>
     *   <li>Unique: Yes - no two tasks can have the same title</li>
     *   <li>Index: Included in unique constraint for efficient lookup</li>
     * </ul>
     *
     * <p><strong>Validation & Constraints:</strong>
     * <ul>
     *   <li>NOT NULL constraint enforced at database level</li>
     *   <li>UNIQUE constraint enforced at database level</li>
     *   <li>Length constraint enforced at database level (50 chars)</li>
     *   <li>Values longer than 50 characters will be truncated by the database</li>
     *   <li>Service layer validates that title is not duplicated for incomplete tasks</li>
     *   <li>Service layer should validate before persistence to avoid data loss and constraint violations</li>
     * </ul>
     *
     * <p><strong>Business Rule:</strong>
     * <ul>
     *   <li>Cannot have two incomplete (completed = false) tasks with the same title</li>
     *   <li>Completed tasks can have duplicate titles (archived tasks don't count)</li>
     *   <li>The service layer enforces this business rule via validation before persistence</li>
     *   <li>Duplicate constraint violations trigger a business exception in the service layer</li>
     * </ul>
     *
     * <p><strong>Data Characteristics:</strong>
     * <ul>
     *   <li>Required Field: Always populated for every task</li>
     *   <li>User-Provided: Set by clients during task creation</li>
     *   <li>Modifiable: Can be updated through the service layer</li>
     *   <li>Searchable: Indexed for efficient queries</li>
     * </ul>
     *
     * <p><strong>Business Purpose:</strong>
     * Provides a brief, human-readable name or summary of the task. Examples include:
     * "Complete project documentation", "Fix authentication bug", etc.
     *
     * <p><strong>Mapping Note:</strong>
     * This field is mapped from the domain Task.title property during entity creation
     * and mapping. The service layer is responsible for setting this before persistence
     * and validating the uniqueness rule.
     */
    @Column(name = "title", nullable = false, length = 50)
    private String title;

    /**
     * The description of the task.
     *
     * <p><strong>Database Properties:</strong>
     * <ul>
     *   <li>Type: VARCHAR(200)</li>
     *   <li>Column Name: {@code description}</li>
     *   <li>Nullable: No - must always have a value</li>
     *   <li>Length: Maximum 200 characters</li>
     *   <li>Index: Can be indexed for searching, though longer fields typically aren't</li>
     * </ul>
     *
     * <p><strong>Validation & Constraints:</strong>
     * <ul>
     *   <li>NOT NULL constraint enforced at database level</li>
     *   <li>Length constraint enforced at database level (200 chars)</li>
     *   <li>Values longer than 200 characters will be truncated by the database</li>
     *   <li>Service layer should validate before persistence to avoid data loss</li>
     * </ul>
     *
     * <p><strong>Data Characteristics:</strong>
     * <ul>
     *   <li>Required Field: Always populated for every task</li>
     *   <li>User-Provided: Set by clients during task creation</li>
     *   <li>Modifiable: Can be updated through the service layer</li>
     *   <li>Multi-line Capable: Can contain newline characters</li>
     * </ul>
     *
     * <p><strong>Business Purpose:</strong>
     * Provides detailed information about the task, including context, objectives,
     * and instructions. Examples include acceptance criteria, step-by-step instructions, etc.
     *
     * <p><strong>Mapping Note:</strong>
     * This field is mapped from the domain Task.description property during entity creation
     * and mapping. The service layer is responsible for setting this before persistence.
     */
    @Column(name = "description", nullable = false, length = 200)
    private String description;

    /**
     * The completion status of the task.
     *
     * <p><strong>Database Properties:</strong>
     * <ul>
     *   <li>Type: BOOLEAN</li>
     *   <li>Column Name: {@code completed}</li>
     *   <li>Nullable: No - must always have a value</li>
     *   <li>Default Value: FALSE (enforced at database level)</li>
     *   <li>Column Definition: {@code BOOLEAN DEFAULT FALSE}</li>
     * </ul>
     *
     * <p><strong>Validation & Constraints:</strong>
     * <ul>
     *   <li>NOT NULL constraint enforced at database level</li>
     *   <li>Default value of FALSE applied by database for new inserts if not explicitly set</li>
     *   <li>Only two valid values: true (complete) or false (incomplete)</li>
     * </ul>
     *
     * <p><strong>Data Characteristics:</strong>
     * <ul>
     *   <li>Default: false (new tasks are incomplete)</li>
     *   <li>Modifiable: Can be toggled by users</li>
     *   <li>State Indicator: Primary indicator of task progress</li>
     *   <li>Efficient Storage: Boolean uses minimal database space</li>
     * </ul>
     *
     * <p><strong>Meaning & Values:</strong>
     * <ul>
     *   <li>{@code false} - Task is pending, incomplete, or in progress</li>
     *   <li>{@code true} - Task is finished, done, or completed</li>
     * </ul>
     *
     * <p><strong>Business Implications:</strong>
     * <ul>
     *   <li>New tasks always start with completed = false</li>
     *   <li>Can be toggled from false to true when work is finished</li>
     *   <li>Can be toggled back from true to false if reopened</li>
     *   <li>Often used for filtering (show incomplete tasks, archived tasks, etc.)</li>
     * </ul>
     *
     * <p><strong>Mapping Note:</strong>
     * This field is mapped from the domain Task.completed property during entity creation
     * and mapping. For new tasks, the service layer sets this to false before persistence.
     */
    @Column(name = "completed", nullable = false, columnDefinition = "BOOLEAN DEFAULT FALSE")
    private boolean completed;

    /**
     * The timestamp when the task was created.
     *
     * <p><strong>Database Properties:</strong>
     * <ul>
     *   <li>Type: TIMESTAMP (LocalDateTime)</li>
     *   <li>Column Name: {@code created_at}</li>
     *   <li>Nullable: No - must always have a value</li>
     *   <li>Format: ISO-8601 extended format (YYYY-MM-DDTHH:mm:ss)</li>
     *   <li>Timezone: Local timezone (no timezone offset stored)</li>
     * </ul>
     *
     * <p><strong>Validation & Constraints:</strong>
     * <ul>
     *   <li>NOT NULL constraint enforced at database level</li>
     *   <li>Set by the service layer before persistence</li>
     *   <li>Immutable in the database (never updated after creation)</li>
     * </ul>
     *
     * <p><strong>Data Characteristics:</strong>
     * <ul>
     *   <li>Set Once: Assigned during task creation and never modified</li>
     *   <li>Server-Generated: Set by service layer to current server time</li>
     *   <li>Precision: Includes seconds (no milliseconds stored by default)</li>
     *   <li>Audit Value: Provides creation audit trail</li>
     * </ul>
     *
     * <p><strong>Example Values:</strong>
     * <ul>
     *   <li>2026-02-19T10:30:45</li>
     *   <li>2026-01-01T00:00:00</li>
     * </ul>
     *
     * <p><strong>Business Uses:</strong>
     * <ul>
     *   <li>Display when a task was created to users</li>
     *   <li>Sort tasks by creation date (oldest/newest first)</li>
     *   <li>Calculate task age or duration</li>
     *   <li>Audit trails and change history</li>
     *   <li>Analytics on task creation patterns</li>
     * </ul>
     *
     * <p><strong>Important Notes:</strong>
     * <ul>
     *   <li>This timestamp is immutable - it never changes after task creation</li>
     *   <li>The service layer is responsible for setting this before persistence</li>
     *   <li>The repository layer does not modify this field</li>
     *   <li>Even when the task is updated, createdAt remains unchanged</li>
     * </ul>
     *
     * <p><strong>Mapping Note:</strong>
     * This field is mapped from the domain Task.createdAt property. The service layer sets
     * this to {@code LocalDateTime.now()} before creating/persisting the entity.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * The timestamp when the task was last updated.
     *
     * <p><strong>Database Properties:</strong>
     * <ul>
     *   <li>Type: TIMESTAMP (LocalDateTime)</li>
     *   <li>Column Name: {@code updated_at}</li>
     *   <li>Nullable: Yes - can be NULL for tasks that have never been updated</li>
     *   <li>Format: ISO-8601 extended format (YYYY-MM-DDTHH:mm:ss)</li>
     *   <li>Timezone: Local timezone (no timezone offset stored)</li>
     * </ul>
     *
     * <p><strong>Validation & Constraints:</strong>
     * <ul>
     *   <li>Nullable constraint - NULL values are allowed</li>
     *   <li>Set by the service layer during updates</li>
     *   <li>Not automatically managed by JPA (service layer is responsible)</li>
     * </ul>
     *
     * <p><strong>Data Characteristics:</strong>
     * <ul>
     *   <li>Initially NULL: New tasks have updatedAt = NULL (no updates yet)</li>
     *   <li>Server-Generated: Set by service layer to current server time on updates</li>
     *   <li>Precision: Includes seconds (no milliseconds stored by default)</li>
     *   <li>Audit Value: Provides modification audit trail</li>
     * </ul>
     *
     * <p><strong>Null Handling:</strong>
     * <ul>
     *   <li>NULL value means: Task has never been updated since creation</li>
     *   <li>Non-NULL value means: Task has been updated at least once</li>
     *   <li>Always: updatedAt >= createdAt (when updatedAt is not NULL)</li>
     * </ul>
     *
     * <p><strong>Example Values:</strong>
     * <ul>
     *   <li>2026-02-19T15:45:30 (task has been updated)</li>
     *   <li>NULL (task has never been updated since creation)</li>
     * </ul>
     *
     * <p><strong>Business Uses:</strong>
     * <ul>
     *   <li>Display when a task was last modified to users</li>
     *   <li>Sort tasks by most recently updated (for activity feeds)</li>
     *   <li>Detect stale data or detect when a task was last touched</li>
     *   <li>Implement optimistic locking and concurrency control</li>
     *   <li>Generate activity logs showing task modification history</li>
     * </ul>
     *
     * <p><strong>Update Triggers:</strong>
     * The updatedAt timestamp is set to the current server time whenever any of the
     * following mutable properties are modified:
     * <ul>
     *   <li>title</li>
     *   <li>description</li>
     *   <li>completed</li>
     * </ul>
     *
     * <p><strong>Important Notes:</strong>
     * <ul>
     *   <li>The service layer is responsible for setting this value on updates</li>
     *   <li>The createdAt timestamp is always preserved and never modified</li>
     *   <li>The repository layer does not automatically update this field</li>
     *   <li>JPA does not automatically manage this field; manual assignment is required</li>
     * </ul>
     *
     * <p><strong>Mapping Note:</strong>
     * This field is mapped from the domain Task.updatedAt property. The service layer is
     * responsible for setting this to {@code LocalDateTime.now()} whenever the task is updated.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_list_id")
    private TaskListEntity taskList;

}
