package com.nsalazar.quicktask.tasklist.domain;

import com.nsalazar.quicktask.task.domain.Task;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Domain model representing a TaskList.
 *
 * <p>A TaskList groups multiple {@link Task} objects under a common name and description.
 * It provides organizational structure for tasks, allowing users to categorize and
 * manage related tasks together.
 *
 * <p><strong>Relationship:</strong>
 * A TaskList has a one-to-many relationship with Task. One TaskList can contain many Tasks,
 * and each Task can belong to at most one TaskList.
 *
 * @author nsalazar
 * @see Task
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaskList {

    /**
     * The unique identifier of the task list.
     *
     * <p>Generated by the database during persistence. Immutable after creation.
     */
    private UUID id;

    /**
     * The name of the task list.
     *
     * <p>Required, unique, maximum 50 characters.
     */
    private String name;

    /**
     * The description of the task list.
     *
     * <p>Required, maximum 200 characters.
     */
    private String description;

    /**
     * The list of tasks associated with this task list.
     *
     * <p>Defaults to an empty list. Tasks are added and removed through the Task service layer.
     */
    @Builder.Default
    private List<Task> tasks = new ArrayList<>();

    /**
     * The timestamp when the task list was created.
     *
     * <p>Set once during creation and never modified.
     */
    private LocalDateTime createdAt;

    /**
     * The timestamp when the task list was last updated.
     *
     * <p>Initially null. Set to the current time whenever the task list is modified.
     */
    private LocalDateTime updatedAt;

}

